name: Test Channel

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  build-dry-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-version: ['1.91', '1.92', '1.93']
    steps:
      - uses: actions/checkout@v4

      - name: Install Guix
        uses: sbellem/guix-install-action@dev
        with:
          version: "1.5.0"
          pullAfterInstall: false

      - name: Dry-run build rust-${{ matrix.rust-version }}
        run: |
          guix time-machine \
            --channels=guix-channel.scm \
            -- build -L packages -e '(@ (rust) rust-${{ matrix.rust-version }})' --dry-run

      - name: Dry-run build default rust
        if: matrix.rust-version == '1.93'
        run: |
          guix time-machine \
            --channels=guix-channel.scm \
            -- build -L packages -e '(@ (rust) rust)' --dry-run

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ['1.91', '1.92', '1.93']
    steps:
      - uses: actions/checkout@v4

      - name: Install Guix
        uses: sbellem/guix-install-action@dev
        with:
          version: "1.5.0"
          pullAfterInstall: false

      - name: Build rust-${{ matrix.rust-version }}
        run: |
          guix time-machine \
            --channels=guix-channel.scm \
            -- build -L packages -e '(@ (rust) rust-${{ matrix.rust-version }})'

  build-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Guix
        uses: sbellem/guix-install-action@dev
        with:
          version: "1.5.0"
          pullAfterInstall: false

      - name: Build default rust
        run: |
          guix time-machine \
            --channels=guix-channel.scm \
            -- build -L packages -e '(@ (rust) rust)'
